[package]
name = "synth"
version = "0.0.0"
edition = "2021"
authors = ["Lauda Carly <lauda@nel.re"]
description = "Simple rust synthesizer"
readme = "README.md"
repository = "https://github.com/n-e-l/synth"
license = "GPL-3.0-only"
keywords = ["compute", "vulkan", "render", "engine", "synth"]
categories = ["rendering::engine"]

[dependencies]
cen = { git = "https://github.com/n-e-l/cen", rev = "241f224b9da41a2c0cf5e59b5f8db6cc515e70c9" }
cpal = "0.13.4"
bytemuck = { version = "1.17.0", features = ["derive"] }
egui_plot = "0.34.1"
egui_code_editor = "0.2.21"
rfd = "0.17.2"

[dev-dependencies]
