#version 450

layout ( local_size_x = 128, local_size_y = 1, local_size_z = 1 ) in;

layout( std430, binding = 0 ) buffer AudioBuffer {
    float[] data;
} audio_data;

layout( push_constant ) uniform PushConstants
{
    float time;
    int samples;
    float frequency;
    float volume;
    float[4] options;
} constants;

audio_function

void main()
{
    int i = int( gl_GlobalInvocationID.x );
    if( i > constants.samples ) return;
    audio_data.data[i] = audio(constants.time + float( i ) / constants.samples, constants.volume, constants.frequency, constants.options).r;
}
