#version 450

layout ( local_size_x = 64, local_size_y = 1, local_size_z = 1 ) in;

layout( std430, binding = 0 ) buffer AudioBuffer {
    float[] data;
} audio_data;

layout( std430, binding = 1 ) buffer MinMaxBuffer {
    vec2[] data;
} minmax_data;

layout( push_constant ) uniform PushConstants
{
    uint samples;
    uint pixels_x;
    uint pixels_y;
    float zoom;
    uint offset;
} constants;

void main()
{
    int pixel = int( gl_GlobalInvocationID.x );
    if( pixel > constants.pixels_x ) return;


    float samples_per_pixel = constants.zoom * constants.samples / float(constants.pixels_x);

    int start_sample = int(floor(constants.offset - constants.samples * constants.zoom / 2. + pixel * samples_per_pixel));
    int end_sample = int(ceil(start_sample + samples_per_pixel + 1));

    // Invalid sample as default
    vec2 minmax = vec2(1., -1.); // Min bigger than max

    if( start_sample > 0 && end_sample < constants.samples ) {
        minmax = vec2(100., -100.);
        for (int i = start_sample; i < end_sample; i++) {
            float s = audio_data.data[i];
            minmax[0] = min(minmax[0], s);
            minmax[1] = max(minmax[1], s);
        }

        // Always fill to zero
        minmax[0] = min(minmax[0], 0.);
        minmax[1] = max(minmax[1], 0.);
    }


    minmax_data.data[ pixel ] = minmax;
}
