#version 450

layout ( local_size_x = 64, local_size_y = 1, local_size_z = 1 ) in;

layout( std430, binding = 0 ) buffer AudioBuffer {
    vec2[] data;
} audio_data;

struct PixelData {
    float minimum;
    float maximum;
    int direction;
    uint sample_index;
};
layout( std430, binding = 1 ) buffer MinMaxBuffer {
    PixelData[] data;
} minmax_data;

layout( push_constant ) uniform PushConstants
{
    uint samples_per_second;
    uint total_samples;
    uint pixels_x;
    uint pixels_y;
    float zoom;
    uint offset;
    uint current_sample;
} constants;

void main()
{
    int pixel = int( gl_GlobalInvocationID.x );
    if( pixel >= constants.pixels_x ) return;

    float samples_per_pixel = constants.zoom * constants.samples_per_second / float(constants.pixels_x);
    float pixel_size_y = 2.0 / constants.pixels_y;

    // The pixel time expressed in individual samples
    float sample_time = constants.offset - constants.samples_per_second * constants.zoom / 2. + pixel * samples_per_pixel;

    int start_sample = int(floor(sample_time));
    int end_sample = int(floor(sample_time + samples_per_pixel));

    // Invalid sample as default
    vec2 minmax = vec2(1., -1.); // Min bigger than max

    int direction = 0;
    uint sample_index = uint(max(start_sample, 0));

    if (start_sample >= 0 && end_sample < int(constants.total_samples)) {
        minmax = vec2(100., -100.);
        for (int i = start_sample; i <= end_sample; i++) {
            float s = audio_data.data[i].x;
            minmax[0] = min(minmax[0], s);
            minmax[1] = max(minmax[1], s);
        }


        float a = audio_data.data[start_sample].x;
        float b = audio_data.data[end_sample].x;
        if (a < b) direction = 1;
        if (a > b) direction = 2;
        if( (minmax[0] != a && minmax[0] != b) || (minmax[1] != a && minmax[1] != b) ) direction = 0;
        sample_index = uint(start_sample);
    }

    minmax_data.data[pixel] = PixelData(minmax[0], minmax[1], direction, sample_index);
}
