#version 450

layout ( local_size_x = 64, local_size_y = 1, local_size_z = 1 ) in;

layout( std430, binding = 0 ) buffer AudioBuffer {
    vec2[] data;
} audio_data;

struct PixelData {
    vec2[2] minmax;
    ivec2 direction;
    uint sample_index;
    uint padding;
};
layout( std430, binding = 1 ) buffer MinMaxBuffer {
    PixelData[] data;
} minmax_data;

layout( push_constant ) uniform PushConstants
{
    uint samples_per_second;
    uint total_samples;
    uint pixels_x;
    uint pixels_y;
    float zoom;
    uint offset;
    uint current_sample;
    uint channel;
} constants;

void main()
{
    int pixel = int( gl_GlobalInvocationID.x );
    if( pixel >= constants.pixels_x ) return;

    float samples_per_pixel = constants.zoom * constants.samples_per_second / float(constants.pixels_x);
    float pixel_size_y = 2.0 / constants.pixels_y;

    // The pixel time expressed in individual samples
    float sample_time = constants.offset - constants.samples_per_second * constants.zoom / 2. + pixel * samples_per_pixel;

    int start_sample = int(floor(sample_time));
    int end_sample = int(floor(sample_time + samples_per_pixel));

    // Invalid sample as default
    vec2[2] minmax = vec2[2](vec2(1., -1.), vec2(1., -1.)); // Min bigger than max

    ivec2 direction = ivec2(0);
    uint sample_index = uint(max(start_sample, 0));

    if (start_sample >= 0 && end_sample < int(constants.total_samples)) {
        for (int i = start_sample; i <= end_sample; i++) {
            vec2 s = audio_data.data[i];
            // Left channel
            minmax[0][0] = min(minmax[0][0], s[0]);
            minmax[0][1] = max(minmax[0][1], s[0]);

            // Right channel
            minmax[1][0] = min(minmax[1][0], s[1]);
            minmax[1][1] = max(minmax[1][1], s[1]);
        }

        vec2 a = audio_data.data[start_sample];
        vec2 b = audio_data.data[end_sample];
        for(int i =0; i< 2; i++) {
            if (a[i] < b[i]) direction[i] = 1;
            if (a[i] > b[i]) direction[i] = 2;
            if( (minmax[i][0] != a[i] && minmax[i][0] != b[i]) || (minmax[i][1] != a[i] && minmax[i][1] != b[i]) ) direction[i] = 0;
            sample_index = uint(start_sample);
        }
    }

    minmax_data.data[pixel] = PixelData(minmax, direction, sample_index, 0);
}
